package com.example.gulcinmobile.ui.components

val strings = mapOf(
    "en" to mapOf(
        "home" to "Home",
        "show_news" to "Show AI and Technology News 💡",
        "error" to "Error",
        "save" to "Save",
        "cancel" to "Cancel",
        "language_selection" to "Select Language",
        "settings" to "Settings",
        "app_title" to "AI News",
        "menu" to "Menu",
        "welcome_message" to "Welcome to AI News App!",
        "select_category" to "Please select a news category from the menu",
        "news_categories" to "News Categories",
        "general_news" to "General News",
        "tech_news" to "Technology News",
        "political_news" to "Political News",
        "sports_news" to "Sports News",
        "business_news" to "Business News",
        "art_news" to "Art News",
        "entertainment_news" to "Entertainment News",
        "show_general_news" to "Show Latest General News",
        "show_tech_news" to "Show Latest Technology News",
        "show_political_news" to "Show Latest Political News",
        "show_sports_news" to "Show Latest Sports News",
        "show_business_news" to "Show Latest Business News",
        "show_art_news" to "Show Latest Art News",
        "show_entertainment_news" to "Show Latest Entertainment News",
        "news" to "News",
        "continue" to "Continue to News App"
    ),
    "tr" to mapOf(
        "home" to "Ana Menü",
        "show_news" to "Yapay Zekâ ve Teknoloji Gelişmelerini Göster 💡",
        "error" to "Hata",
        "save" to "Kaydet",
        "cancel" to "Vazgeç",
        "language_selection" to "Dil Seçimi",
        "settings" to "Ayarlar",
        "app_title" to "Yapay Zeka Haberleri",
        "menu" to "Menü",
        "welcome_message" to "Yapay Zeka Haber Uygulamasına Hoş Geldiniz!",
        "select_category" to "Lütfen menüden bir haber kategorisi seçin",
        "news_categories" to "Haber Kategorileri",
        "general_news" to "Genel Haberler",
        "tech_news" to "Teknoloji Haberleri",
        "political_news" to "Siyasi Haberler",
        "sports_news" to "Spor Haberleri",
        "business_news" to "İş Dünyası Haberleri",
        "art_news" to "Sanat Haberleri",
        "entertainment_news" to "Magazin Haberleri",
        "show_general_news" to "En Son Genel Haberleri Göster",
        "show_tech_news" to "En Son Teknoloji Haberlerini Göster",
        "show_political_news" to "En Son Siyasi Haberleri Göster",
        "show_sports_news" to "En Son Spor Haberlerini Göster",
        "show_business_news" to "En Son İş Dünyası Haberlerini Göster",
        "show_art_news" to "En Son Sanat Haberlerini Göster",
        "show_entertainment_news" to "En Son Magazin Haberlerini Göster",
        "news" to "Haberler",
        "continue" to "Haber Uygulamasına Devam Et"
    ),
    "fr" to mapOf(
        "home" to "Accueil",
        "show_news" to "Afficher les actualités IA et technologie 💡",
        "error" to "Erreur",
        "save" to "Enregistrer",
        "cancel" to "Annuler",
        "language_selection" to "Choisir la langue",
        "settings" to "Paramètres",
        "app_title" to "Actualités IA",
        "menu" to "Menu",
        "welcome_message" to "Bienvenue sur l'application d'actualités IA!",
        "select_category" to "Veuillez sélectionner une catégorie d'actualités dans le menu",
        "news_categories" to "Catégories d'actualités",
        "general_news" to "Actualités générales",
        "tech_news" to "Actualités technologiques",
        "political_news" to "Actualités politiques",
        "sports_news" to "Actualités sportives",
        "business_news" to "Actualités économiques",
        "art_news" to "Actualités artistiques",
        "entertainment_news" to "Actualités de divertissement",
        "show_general_news" to "Afficher les dernières actualités générales",
        "show_tech_news" to "Afficher les dernières actualités technologiques",
        "show_political_news" to "Afficher les dernières actualités politiques",
        "show_sports_news" to "Afficher les dernières actualités sportives",
        "show_business_news" to "Afficher les dernières actualités économiques",
        "show_art_news" to "Afficher les dernières actualités artistiques",
        "show_entertainment_news" to "Afficher les dernières actualités de divertissement",
        "news" to "Actualités",
        "continue" to "Continuer vers l'application d'actualités"
    ),
    "es" to mapOf(
        "home" to "Inicio",
        "show_news" to "Mostrar noticias de IA y tecnología 💡",
        "error" to "Error",
        "save" to "Guardar",
        "cancel" to "Cancelar",
        "language_selection" to "Seleccionar idioma",
        "settings" to "Ajustes",
        "app_title" to "Noticias de IA",
        "menu" to "Menú",
        "welcome_message" to "¡Bienvenido a la aplicación de noticias de IA!",
        "select_category" to "Por favor, seleccione una categoría de noticias del menú",
        "news_categories" to "Categorías de noticias",
        "general_news" to "Noticias generales",
        "tech_news" to "Noticias de tecnología",
        "political_news" to "Noticias políticas",
        "sports_news" to "Noticias deportivas",
        "business_news" to "Noticias de negocios",
        "art_news" to "Noticias de arte",
        "entertainment_news" to "Noticias de entretenimiento",
        "show_general_news" to "Mostrar últimas noticias generales",
        "show_tech_news" to "Mostrar últimas noticias de tecnología",
        "show_political_news" to "Mostrar últimas noticias políticas",
        "show_sports_news" to "Mostrar últimas noticias deportivas",
        "show_business_news" to "Mostrar últimas noticias de negocios",
        "show_art_news" to "Mostrar últimas noticias de arte",
        "show_entertainment_news" to "Mostrar últimas noticias de entretenimiento",
        "news" to "Noticias",
        "continue" to "Continuar a la aplicación de noticias"
    ),
    "de" to mapOf(
        "home" to "Startseite",
        "show_news" to "KI- und Technologie-Nachrichten anzeigen 💡",
        "error" to "Fehler",
        "save" to "Speichern",
        "cancel" to "Abbrechen",
        "language_selection" to "Sprache auswählen",
        "settings" to "Einstellungen",
        "app_title" to "KI-Nachrichten",
        "menu" to "Menü",
        "welcome_message" to "Willkommen bei der KI-Nachrichten-App!",
        "select_category" to "Bitte wählen Sie eine Nachrichtenkategorie aus dem Menü",
        "news_categories" to "Nachrichtenkategorien",
        "general_news" to "Allgemeine Nachrichten",
        "tech_news" to "Technologie-Nachrichten",
        "political_news" to "Politische Nachrichten",
        "sports_news" to "Sport-Nachrichten",
        "business_news" to "Wirtschaftsnachrichten",
        "art_news" to "Kunst-Nachrichten",
        "entertainment_news" to "Unterhaltungsnachrichten",
        "show_general_news" to "Neueste allgemeine Nachrichten anzeigen",
        "show_tech_news" to "Neueste Technologie-Nachrichten anzeigen",
        "show_political_news" to "Neueste politische Nachrichten anzeigen",
        "show_sports_news" to "Neueste Sport-Nachrichten anzeigen",
        "show_business_news" to "Neueste Wirtschaftsnachrichten anzeigen",
        "show_art_news" to "Neueste Kunst-Nachrichten anzeigen",
        "show_entertainment_news" to "Neueste Unterhaltungsnachrichten anzeigen",
        "news" to "Nachrichten",
        "continue" to "Zur Nachrichten-App fortfahren"
    )
)