package com.example.gulcinmobile.ui.components

val strings = mapOf(
    "en" to mapOf(
        "home" to "Home",
        "show_news" to "Show AI and Technology News 💡",
        "error" to "Error",
        "save" to "Save",
        "cancel" to "Cancel",
        "language_selection" to "Select Language",
        "settings" to "Settings",
        "app_title" to "AI News",
        "menu" to "Menu",
        "welcome_message" to "Welcome to AI News App!",
        "select_category" to "Please select a news category from the menu",
        "news_categories" to "News Categories",
        "general_news" to "General News",
        "tech_news" to "Technology News",
        "political_news" to "Political News",
        "sports_news" to "Sports News",
        "business_news" to "Business News",
        "art_news" to "Art News",
        "entertainment_news" to "Entertainment News",
        "ai_news" to "AI News",
        "show_general_news" to "Show Latest General News",
        "show_tech_news" to "Show Latest Technology News",
        "show_political_news" to "Show Latest Political News",
        "show_sports_news" to "Show Latest Sports News",
        "show_business_news" to "Show Latest Business News",
        "show_art_news" to "Show Latest Art News",
        "show_entertainment_news" to "Show Latest Entertainment News",
        "show_ai_news" to "Show Latest AI News",
        "news" to "News",
        "continue" to "Continue to News App",
        "welcome_title" to "Welcome to GulcinMobile",
        "welcome_description" to "Follow the latest developments in every category from AI to politics, from technology to sports by clicking on the topic that interests you from the menu above, and be instantly informed about the world agenda.",
        "tap_to_see_news" to "Click the button to see the news.",
        "loading" to "Loading...",
        "news_detail" to "News Detail",
        "content" to "Content",
        "source" to "Source",
        "go_to_source" to "Go to News Source",
        "content_not_found" to "Content not found",
        "no_image" to "No Image",
        "go_back" to "Go Back",
        "article_not_in_memory" to "The article details could not be found in memory. Try going back and selecting the article again."

    ),
    "tr" to mapOf(
        "home" to "Ana Menü",
        "show_news" to "Yapay Zekâ ve Teknoloji Gelişmelerini Göster 💡",
        "error" to "Hata",
        "save" to "Kaydet",
        "cancel" to "Vazgeç",
        "language_selection" to "Dil Seçimi",
        "settings" to "Ayarlar",
        "app_title" to "Yapay Zeka Haberleri",
        "menu" to "Menü",
        "welcome_message" to "Yapay Zeka Haber Uygulamasına Hoş Geldiniz!",
        "select_category" to "Lütfen menüden bir haber kategorisi seçin",
        "news_categories" to "Haber Kategorileri",
        "general_news" to "Genel Haberler",
        "tech_news" to "Teknoloji Haberleri",
        "political_news" to "Siyasi Haberler",
        "sports_news" to "Spor Haberleri",
        "business_news" to "İş Dünyası Haberleri",
        "art_news" to "Sanat Haberleri",
        "entertainment_news" to "Magazin Haberleri",
        "ai_news" to "Yapay Zeka Haberleri",
        "show_general_news" to "En Son Genel Haberleri Göster",
        "show_tech_news" to "En Son Teknoloji Haberlerini Göster",
        "show_political_news" to "En Son Siyasi Haberleri Göster",
        "show_sports_news" to "En Son Spor Haberlerini Göster",
        "show_business_news" to "En Son İş Dünyası Haberlerini Göster",
        "show_art_news" to "En Son Sanat Haberlerini Göster",
        "show_entertainment_news" to "En Son Magazin Haberlerini Göster",
        "show_ai_news" to "En Son Yapay Zeka Haberlerini Göster",
        "news" to "Haberler",
        "continue" to "Haber Uygulamasına Devam Et",
        "welcome_title" to "GulcinMobile'a Hoş Geldiniz",
        "welcome_description" to "En güncel gelişmeleri, yapay zekâdan siyasete, teknolojiden spora kadar her kategoride takip etmek için yukarıdaki menüden ilgini çeken başlığa tıklayarak göz atabilir, dünya gündeminden anında haberdar olabilirsiniz.",
        "tap_to_see_news" to "Haberleri görmek için butona tıklayın.",
        "loading" to "Yükleniyor...",
        "news_detail" to "Haber Detayı",
        "content" to "İçerik",
        "source" to "Kaynak",
        "go_to_source" to "Haber Kaynağına Git",
        "content_not_found" to "İçerik bulunamadı",
        "no_image" to "Görsel Yok",
        "go_back" to "Geri Dön",
        "article_not_in_memory" to "Haber detayları hafızada bulunamadı. Geri dönüp haberi tekrar seçmeyi deneyin."

    ),
    "fr" to mapOf(
        "home" to "Accueil",
        "show_news" to "Afficher les actualités IA et technologie 💡",
        "error" to "Erreur",
        "save" to "Enregistrer",
        "cancel" to "Annuler",
        "language_selection" to "Choisir la langue",
        "settings" to "Paramètres",
        "app_title" to "Actualités IA",
        "menu" to "Menu",
        "welcome_message" to "Bienvenue sur l'application d'actualités IA!",
        "select_category" to "Veuillez sélectionner une catégorie d'actualités dans le menu",
        "news_categories" to "Catégories d'actualités",
        "general_news" to "Actualités générales",
        "tech_news" to "Actualités technologiques",
        "political_news" to "Actualités politiques",
        "sports_news" to "Actualités sportives",
        "business_news" to "Actualités économiques",
        "art_news" to "Actualités artistiques",
        "entertainment_news" to "Actualités de divertissement",
        "ai_news" to "Actualités IA",
        "show_general_news" to "Afficher les dernières actualités générales",
        "show_tech_news" to "Afficher les dernières actualités technologiques",
        "show_political_news" to "Afficher les dernières actualités politiques",
        "show_sports_news" to "Afficher les dernières actualités sportives",
        "show_business_news" to "Afficher les dernières actualités économiques",
        "show_art_news" to "Afficher les dernières actualités artistiques",
        "show_entertainment_news" to "Afficher les dernières actualités de divertissement",
        "show_ai_news" to "Afficher les dernières actualités IA",
        "news" to "Actualités",
        "continue" to "Continuer vers l'application d'actualités",
        "welcome_title" to "Bienvenue sur GulcinMobile",
        "welcome_description" to "Suivez les derniers développements dans chaque catégorie, de l'IA à la politique, de la technologie au sport, en cliquant sur le sujet qui vous intéresse dans le menu ci-dessus, et soyez instantanément informé de l'actualité mondiale.",
        "tap_to_see_news" to "Cliquez sur le bouton pour voir les actualités.",
        "loading" to "Chargement...",
        "news_detail" to "Détail de l'actualité",
        "content" to "Contenu",
        "source" to "Source",
        "go_to_source" to "Aller à la source",
        "content_not_found" to "Contenu non trouvé",
        "no_image" to "Pas d'image",
        "go_back" to "Retour",
        "article_not_in_memory" to "Les détails de l'article n'ont pas pu être trouvés en mémoire. Essayez de revenir en arrière et de sélectionner à nouveau l'article."
        ),
    "es" to mapOf(
        "home" to "Inicio",
        "show_news" to "Mostrar noticias de IA y tecnología 💡",
        "error" to "Error",
        "save" to "Guardar",
        "cancel" to "Cancelar",
        "language_selection" to "Seleccionar idioma",
        "settings" to "Ajustes",
        "app_title" to "Noticias de IA",
        "menu" to "Menú",
        "welcome_message" to "¡Bienvenido a la aplicación de noticias de IA!",
        "select_category" to "Por favor, seleccione una categoría de noticias del menú",
        "news_categories" to "Categorías de noticias",
        "general_news" to "Noticias generales",
        "tech_news" to "Noticias de tecnología",
        "political_news" to "Noticias políticas",
        "sports_news" to "Noticias deportivas",
        "business_news" to "Noticias de negocios",
        "art_news" to "Noticias de arte",
        "entertainment_news" to "Noticias de entretenimiento",
        "ai_news" to "Noticias de IA",
        "show_general_news" to "Mostrar últimas noticias generales",
        "show_tech_news" to "Mostrar últimas noticias de tecnología",
        "show_political_news" to "Mostrar últimas noticias políticas",
        "show_sports_news" to "Mostrar últimas noticias deportivas",
        "show_business_news" to "Mostrar últimas noticias de negocios",
        "show_art_news" to "Mostrar últimas noticias de arte",
        "show_entertainment_news" to "Mostrar últimas noticias de entretenimiento",
        "show_ai_news" to "Mostrar últimas noticias de IA",
        "news" to "Noticias",
        "continue" to "Continuar a la aplicación de noticias",
        "welcome_title" to "Bienvenido a GulcinMobile",
        "welcome_description" to "Siga los últimos desarrollos en cada categoría, desde IA hasta política, desde tecnología hasta deportes, haciendo clic en el tema que le interese en el menú de arriba, y esté instantáneamente informado sobre la agenda mundial.",
        "tap_to_see_news" to "Haga clic en el botón para ver las noticias.",
        "loading" to "Cargando...",
        "news_detail" to "Detalle de la noticia",
        "content" to "Contenido",
        "source" to "Fuente",
        "go_to_source" to "Ir a la fuente",
        "content_not_found" to "Contenido no encontrado",
        "no_image" to "Sin imagen",
        "go_back" to "Volver",
        "article_not_in_memory" to "Los detalles del artículo no se pudieron encontrar en la memoria. Intente volver atrás y seleccionar el artículo nuevamente."

        ),
    "de" to mapOf(
        "home" to "Startseite",
        "show_news" to "KI- und Technologie-Nachrichten anzeigen 💡",
        "error" to "Fehler",
        "save" to "Speichern",
        "cancel" to "Abbrechen",
        "language_selection" to "Sprache auswählen",
        "settings" to "Einstellungen",
        "app_title" to "KI-Nachrichten",
        "menu" to "Menü",
        "welcome_message" to "Willkommen bei der KI-Nachrichten-App!",
        "select_category" to "Bitte wählen Sie eine Nachrichtenkategorie aus dem Menü",
        "news_categories" to "Nachrichtenkategorien",
        "general_news" to "Allgemeine Nachrichten",
        "tech_news" to "Technologie-Nachrichten",
        "political_news" to "Politische Nachrichten",
        "sports_news" to "Sport-Nachrichten",
        "business_news" to "Wirtschaftsnachrichten",
        "art_news" to "Kunst-Nachrichten",
        "entertainment_news" to "Unterhaltungsnachrichten",
        "ai_news" to "KI-Nachrichten",
        "show_general_news" to "Neueste allgemeine Nachrichten anzeigen",
        "show_tech_news" to "Neueste Technologie-Nachrichten anzeigen",
        "show_political_news" to "Neueste politische Nachrichten anzeigen",
        "show_sports_news" to "Neueste Sport-Nachrichten anzeigen",
        "show_business_news" to "Neueste Wirtschaftsnachrichten anzeigen",
        "show_art_news" to "Neueste Kunst-Nachrichten anzeigen",
        "show_entertainment_news" to "Neueste Unterhaltungsnachrichten anzeigen",
        "show_ai_news" to "Neueste KI-Nachrichten anzeigen",
        "news" to "Nachrichten",
        "continue" to "Zur Nachrichten-App fortfahren",
        "welcome_title" to "Willkommen bei GulcinMobile",
        "welcome_description" to "Verfolgen Sie die neuesten Entwicklungen in jeder Kategorie, von KI bis Politik, von Technologie bis Sport, indem Sie im obigen Menü auf das Thema klicken, das Sie interessiert, und werden Sie sofort über die Weltlage informiert.",
        "tap_to_see_news" to "Klicken Sie auf die Schaltfläche, um die Nachrichten zu sehen.",
        "loading" to "Wird geladen...",
        "news_detail" to "Nachrichtendetail",
        "content" to "Inhalt",
        "source" to "Quelle",
        "go_to_source" to "Zur Quelle gehen",
        "content_not_found" to "Inhalt nicht gefunden",
        "no_image" to "Kein Bild",
        "go_back" to "Zurück",
        "article_not_in_memory" to "Die Artikeldetails konnten im Speicher nicht gefunden werden. Versuchen Sie, zurückzugehen und den Artikel erneut auszuwählen."

        ),
    "ja" to mapOf(
        "home" to "ホーム",
        "show_news" to "AIとテクノロジーのニュースを表示 💡",
        "error" to "エラー",
        "save" to "保存",
        "cancel" to "キャンセル",
        "language_selection" to "言語を選択",
        "settings" to "設定",
        "app_title" to "AIニュース",
        "menu" to "メニュー",
        "welcome_message" to "AIニュースアプリへようこそ！",
        "select_category" to "メニューからニュースカテゴリを選択してください",
        "news_categories" to "ニュースカテゴリ",
        "general_news" to "一般ニュース",
        "tech_news" to "テクノロジーニュース",
        "political_news" to "政治ニュース",
        "sports_news" to "スポーツニュース",
        "business_news" to "ビジネスニュース",
        "art_news" to "アートニュース",
        "entertainment_news" to "エンタメニュース",
        "ai_news" to "AIニュース",
        "show_general_news" to "最新の一般ニュースを表示",
        "show_tech_news" to "最新のテクノロジーニュースを表示",
        "show_political_news" to "最新の政治ニュースを表示",
        "show_sports_news" to "最新のスポーツニュースを表示",
        "show_business_news" to "最新のビジネスニュースを表示",
        "show_art_news" to "最新のアートニュースを表示",
        "show_entertainment_news" to "最新のエンタメニュースを表示",
        "show_ai_news" to "最新のAIニュースを表示",
        "news" to "ニュース",
        "continue" to "ニュースアプリへ進む",
        "welcome_title" to "GulcinMobileへようこそ",
        "welcome_description" to "上記のメニューから興味のあるトピックをクリックして、AIから政治、テクノロジーからスポーツまで、あらゆるカテゴリの最新情報をフォローし、世界の議題について即座に情報を得ることができます。",
        "tap_to_see_news" to "ニュースを見るにはボタンをクリックしてください。",
        "loading" to "読み込み中...",
        "news_detail" to "ニュース詳細",
        "content" to "コンテンツ",
        "source" to "ソース",
        "go_to_source" to "ニュースソースへ",
        "content_not_found" to "コンテンツが見つかりません",
        "no_image" to "画像なし",
        "go_back" to "戻る",
        "article_not_in_memory" to "記事の詳細がメモリに見つかりませんでした。戻って記事を再度選択してみてください。"

        ),
    "ar" to mapOf(
        "home" to "الرئيسية",
        "show_news" to "عرض أخبار الذكاء الاصطناعي والتكنولوجيا 💡",
        "error" to "خطأ",
        "save" to "حفظ",
        "cancel" to "إلغاء",
        "language_selection" to "اختيار اللغة",
        "settings" to "الإعدادات",
        "app_title" to "أخبار الذكاء الاصطناعي",
        "menu" to "القائمة",
        "welcome_message" to "مرحبًا بك في تطبيق أخبار الذكاء الاصطناعي!",
        "select_category" to "يرجى اختيار فئة الأخبار من القائمة",
        "news_categories" to "فئات الأخبار",
        "general_news" to "أخبار عامة",
        "tech_news" to "أخبار التكنولوجيا",
        "political_news" to "أخبار سياسية",
        "sports_news" to "أخبار رياضية",
        "business_news" to "أخبار الأعمال",
        "art_news" to "أخبار الفن",
        "entertainment_news" to "أخبار الترفيه",
        "ai_news" to "أخبار الذكاء الاصطناعي",
        "show_general_news" to "عرض آخر الأخبار العامة",
        "show_tech_news" to "عرض آخر أخبار التكنولوجيا",
        "show_political_news" to "عرض آخر الأخبار السياسية",
        "show_sports_news" to "عرض آخر الأخبار الرياضية",
        "show_business_news" to "عرض آخر أخبار الأعمال",
        "show_art_news" to "عرض آخر أخبار الفن",
        "show_entertainment_news" to "عرض آخر أخبار الترفيه",
        "show_ai_news" to "عرض آخر أخبار الذكاء الاصطناعي",
        "news" to "الأخبار",
        "continue" to "الانتقال إلى تطبيق الأخبار",
        "welcome_title" to "مرحبًا بك في GulcinMobile",
        "welcome_description" to "تابع أحدث التطورات في كل فئة من الذكاء الاصطناعي إلى السياسة، ومن التكنولوجيا إلى الرياضة من خلال النقر على الموضوع الذي يهمك من القائمة أعلاه، وكن على اطلاع فوري بجدول أعمال العالم.",
        "tap_to_see_news" to "انقر على الزر لرؤية الأخبار.",
        "loading" to "جار التحميل...",
        "news_detail" to "تفاصيل الخبر",
        "content" to "المحتوى",
        "source" to "المصدر",
        "go_to_source" to "الذهاب إلى المصدر",
        "content_not_found" to "المحتوى غير موجود",
        "no_image" to "لا توجد صورة",
        "go_back" to "العودة",
        "article_not_in_memory" to "تعذر العثور على تفاصيل المقالة في الذاكرة. حاول العودة واختيار المقالة مرة أخرى."


        ),
    "ru" to mapOf(
        "home" to "Главная",
        "show_news" to "Показать новости об ИИ и технологиях 💡",
        "error" to "Ошибка",
        "save" to "Сохранить",
        "cancel" to "Отмена",
        "language_selection" to "Выбор языка",
        "settings" to "Настройки",
        "app_title" to "Новости ИИ",
        "menu" to "Меню",
        "welcome_message" to "Добро пожаловать в приложение новостей ИИ!",
        "select_category" to "Пожалуйста, выберите категорию новостей из меню",
        "news_categories" to "Категории новостей",
        "general_news" to "Общие новости",
        "tech_news" to "Новости технологий",
        "political_news" to "Политические новости",
        "sports_news" to "Спортивные новости",
        "business_news" to "Деловые новости",
        "art_news" to "Новости искусства",
        "entertainment_news" to "Новости развлечений",
        "ai_news" to "Новости ИИ",
        "show_general_news" to "Показать последние общие новости",
        "show_tech_news" to "Показать последние новости технологий",
        "show_political_news" to "Показать последние политические новости",
        "show_sports_news" to "Показать последние спортивные новости",
        "show_business_news" to "Показать последние деловые новости",
        "show_art_news" to "Показать последние новости искусства",
        "show_entertainment_news" to "Показать последние новости развлечений",
        "show_ai_news" to "Показать последние новости ИИ",
        "news" to "Новости",
        "continue" to "Перейти к приложению новостей",
        "welcome_title" to "Добро пожаловать в GulcinMobile",
        "welcome_description" to "Следите за последними событиями в каждой категории, от ИИ до политики, от технологий до спорта, нажав на интересующую вас тему в меню выше, и мгновенно получайте информацию о мировой повестке дня.",
        "tap_to_see_news" to "Нажмите на кнопку, чтобы увидеть новости.",
        "loading" to "Загрузка...",
        "news_detail" to "Детали новости",
        "content" to "Содержание",
        "source" to "Источник",
        "go_to_source" to "Перейти к источнику",
        "content_not_found" to "Содержание не найдено",
        "no_image" to "Нет изображения",
        "go_back" to "Назад",
        "article_not_in_memory" to "Детали статьи не удалось найти в памяти. Попробуйте вернуться назад и выбрать статью снова."


        ),
    "zh" to mapOf(
        "home" to "首页",
        "show_news" to "显示人工智能与科技新闻 💡",
        "error" to "错误",
        "save" to "保存",
        "cancel" to "取消",
        "language_selection" to "选择语言",
        "settings" to "设置",
        "app_title" to "人工智能新闻",
        "menu" to "菜单",
        "welcome_message" to "欢迎使用人工智能新闻应用！",
        "select_category" to "请从菜单中选择一个新闻类别",
        "news_categories" to "新闻类别",
        "general_news" to "综合新闻",
        "tech_news" to "科技新闻",
        "political_news" to "政治新闻",
        "sports_news" to "体育新闻",
        "business_news" to "商业新闻",
        "art_news" to "艺术新闻",
        "entertainment_news" to "娱乐新闻",
        "ai_news" to "人工智能新闻",
        "show_general_news" to "显示最新综合新闻",
        "show_tech_news" to "显示最新科技新闻",
        "show_political_news" to "显示最新政治新闻",
        "show_sports_news" to "显示最新体育新闻",
        "show_business_news" to "显示最新商业新闻",
        "show_art_news" to "显示最新艺术新闻",
        "show_entertainment_news" to "显示最新娱乐新闻",
        "show_ai_news" to "显示最新人工智能新闻",
        "news" to "新闻",
        "continue" to "继续进入新闻应用",
        "welcome_title" to "欢迎使用GulcinMobile",
        "welcome_description" to "通过点击上面菜单中您感兴趣的主题，关注从人工智能到政治、从技术到体育等各个类别的最新发展，并即时了解世界议程。",
        "tap_to_see_news" to "点击按钮查看新闻。",
        "loading" to "加载中...",
        "news_detail" to "新闻详情",
        "content" to "内容",
        "source" to "来源",
        "go_to_source" to "前往新闻来源",
        "content_not_found" to "未找到内容",
        "no_image" to "无图片",
        "go_back" to "返回",
        "article_not_in_memory" to "在内存中找不到文章详情。请尝试返回并重新选择文章。"
    )
)
